import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="flex justify-between items-center p-4 border-b">
          <div className="text-xl font-bold">Rovari</div>
          <nav>
            <ul className="flex space-x-4">
              <li><a href="#services" className="hover:underline">Services</a></li>
              <li><a href="#countries" className="hover:underline">Countries</a></li>
              <li><a href="#resources" className="hover:underline">Resources/Blog</a></li>
              <li><a href="#about" className="hover:underline">About</a></li>
              <li><a href="#contact" className="hover:underline">Contact</a></li>
              <li><a href="#client-portal" className="hover:underline">Client Portal</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}

